language: java

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew tap caskroom/cask; brew install Caskroom/cask/java; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use oraclejdk8; fi


env:
    - CMD="mvn verify -B"; INSTALL="mvn install -DskipTests=true -B"
    - CMD="./gradlew check";


script: eval $CMD
install: eval $INSTALL
