language: java

os:
    - linux
    - osx

before_install:
    - echo "ALEX :::  ${TRAVIS_OS_NAME}"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; echo "ALEX:: mac"; brew cask install java; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "ALEX:: linux"; jdk_switcher use oraclejdk8; fi
