dist: xenial
osx_image: xcode9.4

language: java

os:
    - linux
    - osx

jdk:
    - openjdk8

env:
    - CMD="mvn verify -B"
    - CMD="cd  nondex-gradle-plugin; ./gradlew check";

matrix:
    allow_failures:
        - os: osx

script: eval $CMD
