dist: xenial

language: java

os:
    - linux
    - osx

jdk:
    - openjdk8

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew tap caskroom/cask; brew install Caskroom/cask/java; fi


env:
    - CMD="mvn verify -B"
    - CMD="cd  nondex-gradle-plugin; ./gradlew check";


script: eval $CMD
