/*
The MIT License (MIT)
Copyright (c) 2015 University of Illinois

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

package edu.illinois.nondex.common;

import java.io.File;

public class ConfigurationDefaults {

    // TODO: This should be autogenerated and not needed to be changed manually
    public static final String VERSION = "1.0-SNAPSHOT";


    public static final String PROPERTY_DEFAULT_MODE = "nondex.mode";
    public static final String DEFAULT_MODE_STR = "FULL";
    public static final Mode DEFAULT_MODE = Mode.valueOf(DEFAULT_MODE_STR);


    public static final String PROPERTY_DEFAULT_SEED = "nondex.seed";
    public static final String DEFAULT_SEED_STR = "43258";
    public static final int DEFAULT_SEED = new Integer(DEFAULT_SEED_STR);

    public static final String PROPERTY_DEFAULT_FILTER = "nondex.filter";
    public static final String DEFAULT_FILTER = ".*";

    public static final String PROPERTY_DEFAULT_START = "nondex.start";
    public static final String DEFAULT_START_STR = "0";
    public static final long DEFAULT_START = new Long(DEFAULT_START_STR);

    public static final String PROPERTY_DEFAULT_END = "nondex.end";
    public static final String DEFAULT_END_STR = Long.toString(Long.MAX_VALUE);
    public static final long DEFAULT_END = new Long(DEFAULT_END_STR);

    public static final String PROPERTY_DEFAULT_EXECUTION_ID = "nondex.execid";
    public static final String NO_EXECUTION_ID = "NoId";


    public static final String NONDEX_DIR = ".nondex";
    public static final String FAILURES_FILE = "failures";
    public static final String INVOCATIONS_FILE = "invocations";
    public static final String CONFIGURATION_FILE = "config";

    public static void createNondexDirIfNeeded() {
        new File(ConfigurationDefaults.NONDEX_DIR).mkdir();
    }

}
